[
  {
    id: 1,
    first_name: 'Catherine',
    last_name: 'Widjaja',
    verified: true,
    deleted: false,
    user_roles: ['User'],
  },
  {
    id: 2,
    first_name: 'David',
    last_name: 'Miller',
    verified: true,
    deleted: false,
    user_roles: ['Admin', 'Super Admin'],
  },
  {
    id: 3,
    first_name: 'Domenik',
    last_name: 'Adamoski',
    verified: true,
    deleted: false,
    user_roles: ['Admin'],
  },
  {
    id: 4,
    first_name: 'Duy',
    last_name: 'Tran',
    verified: false,
    deleted: false,
    user_roles: ['User'],
  },
  {
    id: 5,
    first_name: 'Grace',
    last_name: 'Cho',
    verified: true,
    deleted: false,
    user_roles: ['User'],
  },
  {
    id: 6,
    first_name: 'Jenna',
    last_name: 'Pegg',
    verified: true,
    deleted: false,
    user_roles: ['Admin'],
  },
  {
    id: 7,
    first_name: 'John',
    last_name: 'Seo',
    verified: true,
    deleted: false,
    user_roles: ['Admin'],
  },
  {
    id: 8,
    first_name: 'Kade',
    last_name: 'Gray',
    verified: false,
    deleted: false,
    user_roles: ['Admin'],
  },
];
